
os:
  - linux
  # - osx

language: erlang

otp_release:
   - 18.0
   # - 18.1
   # - 18.2
   # - 18.2.1
   # - 18.3

install:
  - sudo apt-get update && sudo apt-get --assume-yes install zip 

script: 
  - make
  - make rel

after_success:
  - python2 scripts/release.py

